baseURL = 'https://blog.viaodyssey.net/'
languageCode = 'fr-fr'
title = 'Via Odyssey â€” Blog'
theme = "my-theme"

[params]
rss_summary = false

[outputs]
home = ["HTML", "RSS"]

[outputFormats.RSS]
baseName = "feed"

[services.rss]
limit = 20

[menu]
[[menu.main]]
name = "ğŸ¥ Videos on Instagram"
url = "https://www.instagram.com/via.odyssey/"
weight = 2

[[menu.main]]
name = "ğŸ—ºï¸ Check Progress Map"
url = "https://viaodyssey.net/viaodyssey"
weight = 3

[[menu.main]]
name = "ğŸ’¬ Micro Blog"
url = "https://mountains.social/@viaodyssey"
weight = 4

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
